export default {
    SET_SIGN_IN_DATA: "SET_SIGN_IN_DATA",
    SET_FORGOT_PASSWORD_DATA: "SET_FORGOT_PASSWORD_DATA",
    SET_PROFILE_NAME_DATA: "SET_PROFILE_NAME_DATA",
    SET_PROFILE_CONTACTS_DATA: "SET_PROFILE_CONTACTS_DATA",
    SET_CONTACT_DETAIL_DATA: "SET_CONTACT_DETAIL_DATA",
    SET_PROFILE_ORGS_DATA: "SET_PROFILE_ORGS_DATA",
    SET_USER_BROADCASTS_DATA: "SET_USER_BROADCASTS_DATA",
    SET_BROADCAST_DETAIL_DATA: "SET_BROADCAST_DETAIL_DATA",
    SET_ADMIN_ORG_DATA: "SET_ADMIN_ORG_DATA",
    SET_ADMIN_USERS_DATA: "SET_ADMIN_USERS_DATA",
    SET_ADMIN_USER_DETAIL_DATA: "SET_ADMIN_USER_DETAIL_DATA",
    SET_ADMIN_GROUPS_DATA: "SET_ADMIN_GROUPS_DATA",
    SET_ADMIN_GROUP_DETAIL_DATA: "SET_ADMIN_GROUP_DETAIL_DATA",
    SET_ADMIN_BROADCASTS_DATA: "SET_ADMIN_BROADCASTS_DATA",

    SERVER: "http://10.0.2.2:8000",

    URL_ISAUTH: "auth/isauth",
    URL_LOGOUT: "logout?applogout",
    URL_SIGNIN: "auth/login",
    URL_PROFILE: "api/profile",
    URL_CONTACTS: "api/contacts",
    URL_USERORGS: "api/orgs",
    URL_USER_BROADCASTS: "api/broadcasts",
    URL_ADMIN_USERS: "api/admin/users",
    URL_ADMIN_USERS_ADMIN: "api/admin/users/admin",
    URL_ADMIN_USERS_NAME: "api/admin/users/name",
    URL_ADMIN_USERS_APPROVE: "api/admin/users/approve",
    URL_ADMIN_USERS_HIDE: "api/admin/users/hide",
    URL_ADMIN_USERS_REMOVE: "api/admin/users/remove",
    URL_ADMIN_USERS_UNHIDE: "api/admin/users/unhide",
    URL_ADMIN_GROUPS: "api/admin/groups",
    URL_ADMIN_GROUPS_REMOVE: "api/admin/groups/remove",
    URL_ADMIN_GROUP_MEMBERS: "api/admin/groups/members",
    URL_ADMIN_GROUP_NONMEMBERS: "api/admin/groups/nonmembers",
    URL_ADMIN_GROUP_RENAME: "api/admin/groups/name",
    URL_ADMIN_BROADCASTS: "api/admin/broadcasts",
    URL_ADMIN_BROADCASTS_GROUPS: "api/admin/broadcasts/groups",
    URL_ADMIN_BROADCASTS_NEW: "api/admin/broadcasts/new"
};
